export const INPUT_FROM_NAME = 'INPUT_FROM_NAME'
export const INPUT_FROM_MAIL = 'INPUT_FROM_MAIL'
export const INPUT_TO_NAME = 'INPUT_TO_NAME'
export const INPUT_TO_MAIL = 'INPUT_TO_MAIL'
export const INPUT_TO_SUBJECT = 'INPUT_TO_SUBJECT'
export const INPUT_TO_MESSAGE = 'INPUT_TO_MESSAGE'

export const INPUT_GETTING_FILES = 'INPUT_GETTING_FILES'
export const INPUT_PROCESSING_FILES_STARTED = 'INPUT_PROCESSING_FILES_STARTED'
export const INPUT_PROCESSING_FILES_FINISHED = 'INPUT_PROCESSING_FILES_FINISHED'

export const ERROR_FILE_LENGTH = 'ERROR_FILE_LENGTH'
export const ERROR_ATTACHMENT_LENGTH = 'ERROR_ATTACHMENT_LENGTH'
export const ERROR_FILE_MIME_TYPE = 'ERROR_FILE_MIME_TYPE'

export const BUTTON_FILES_CLICKED = 'BUTTON_FILES_CLICKED'
export const BUTTON_SUBMIT_CLICKED = 'BUTTON_SUBMIT_CLICKED'
